Feat/task 07
IgorBerezhnoy/Aston_Project_Rick_And_Morty pull request #37
Opened 2024-03-24 13:38 UTC by MolchanovEG

Add page character discription.

2024-03-24 13:54 UTC, DocMoro commented on src/components/characterLabel/characterLabel.tsx
> +export const CharacterLabel = (labelText: Label) => {
Используй деструкторизацию, а то получается объект labelText с единственным полем text

2024-03-24 13:54 UTC, IgorBerezhnoy requested changes

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterLabel/characterLabel.tsx
> +}
А ты на чужих ошибках не учишься😁
Только сегодня сколько дифирамб было отдано интерфейсам

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterPage/characterPage.scss
Почему без модулей?

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterLabel/characterLabel.tsx
> +}
деструктуризация

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterPage/characterPage.stories.tsx
> +}
А почему не в объект?

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterPage/characterPage.tsx
> +import './characterPage.scss'
Модули

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterPage/characterPage.tsx
> +export interface ICharacterPage {
type

2024-03-24 13:54 UTC, IgorBerezhnoy commented on src/components/characterPlaceholder/characterPlaceholder.tsx
> +export interface Placeholder {
type

2024-03-25 07:12 UTC, IgorBerezhnoy approved these changes

2024-03-25 07:12 UTC, merged