ASTON-18: added filters and search
IgorBerezhnoy/Aston_Project_Rick_And_Morty pull request #43
Opened 2024-03-25 21:35 UTC by DocMoro

- Добавил переход на страницу персонажа
- Добавил компоненты поиска и фильтров
- Добавил стили
- Добавил адаптивный вариант для мобильных устройств
- Добавил логику работы фильтрации и поиска
- Исправил ошибку работы модулей
- Скомпоновал страницу поиска

2024-03-26 05:21 UTC, IgorBerezhnoy requested changes

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/page/search-page/search-page.tsx
> +          <CharacterList chars={chars} style={{ marginTop: '65px' }} />
ИнЛайн стили что!? переделай на класс

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/page/search-page/search-page.tsx
> +            stepValue={5}
Магическое число

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/router.tsx
>    {
Что? зачем?

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/characterCard/characterCard.tsx
> +      <Link className={s.card__link} to={`/character/${id}`}>
Енамки с урлом шутка для тебя?

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/characterList/characterList.tsx
> +    <div className={`${s.character}`} style={arg.style}>
Сделай 2 класса используй библиотеку clsx не используй инлайн стили

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/filters/filters.tsx
> +    <article className={`${s.RadioGroup}`} style={arg.style}>
Сделай 2 класса используй библиотеку clsx не используй инлайн стили

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/filtersContainer/filtersContainer.tsx
> +    <div className={`${s.popup} ${isPopup ? s.popup_active : ''}`} onClick={handlePopup}>
clsx

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/radio/radio.stories.tsx
> +    <Root style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
class

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/components/radio/radio.tsx
> +}
type

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/page/search-page/search-page.tsx
> +      navigate(`/search/${nextPage}`)
енам что зря делал?

2024-03-26 05:21 UTC, IgorBerezhnoy commented on src/page/search-page/search-page.tsx
> +  }, [urlParams])
Прости тут плохо понятно, (может зря наезжаю😂) ну лучше хуки поставить повыше перед Ифом "правила хуков"

2024-03-26 07:27 UTC, ElfistIO commented on src/constants/constants.ts
> +export { genders, statuses }
лучше сделать рядом index.ts и export * from './constants.ts'

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +  const handleButtonClier = () => {
handleButtonClear

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
используйте просто SyntethicEvent

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +export default useResourceFiltering
именованный экспорт

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +          count: 20,
Можно вынести в константу

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +  const isDesctop = width > 910
в утилиты

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +  }, [urlParams])
не, тут вроде все норм, if  к другому блоку относится

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +  const isDesctop = width > 910
и isDesktop

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +  const handleSearch = (name: string, value: string) => {
useCallback

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +  const handleButtonClier = () => {
useCallback

2024-03-26 07:27 UTC, ElfistIO commented on src/hooks/use-resource-filtering.ts
> +  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
useCallback

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +        <Search clearValue={handleButtonClier} onChange={handleChange} value={search.name} />
Search  в memo?

2024-03-26 07:27 UTC, ElfistIO commented on src/components/filters/filters.tsx
> +export const Filters: FC<IFilters> = ({ cbClier, cbRadio, state, ...arg }) => {
В memo

2024-03-26 07:27 UTC, ElfistIO commented on src/page/search-page/search-page.tsx
> +            stepValue={5}
Можно в константы

2024-03-26 07:27 UTC, ElfistIO commented on src/service/ResoursesService/CharactersApi.ts
> +      const response = await api.get<Response<Character[]>>(`/character/?page=${page}${params}`)
enum

2024-03-26 07:53 UTC, IgorBerezhnoy commented on src/service/ResoursesService/CharactersApi.ts
> +      const response = await api.get<Response<Character[]>>(`/character/?page=${page}${params}`)
Упс😅 это был внутренний ПР, мы обычно проводим ревью перед тем как вам отправить😅

2024-03-26 17:11 UTC, IgorBerezhnoy commented on src/page/search-page/search-page-container.tsx
> +      <FiltersContainer
Что это такое? < Button >Filters< / Button >

2024-03-26 21:05 UTC, DocMoro commented on src/components/filters/filters.module.scss
> +    font-size: --font-size-l;
Дыа, но можно и обернуть

2024-03-27 13:50 UTC, ElfistIO commented on src/components/filters/filters.module.scss
> +    font-size: --font-size-l;
нужно

2024-03-27 14:00 UTC, ElfistIO approved these changes

2024-03-27 14:00 UTC, ElfistIO commented on src/components/characterCard/characterCard.tsx
> +      <Link className={s.card__link} to={`/character/${id}`}>
Поменять на enum

2024-03-27 14:00 UTC, ElfistIO commented on src/components/filters/filters.tsx
> +  const handleGender = (value: string) => cbRadio('gender', value)
Вот эти строки 'gender', 'status' и другие тоже можно вынести в константы

2024-03-27 14:41 UTC, merged